#!/bin/bash
# Wordpress Maintenance Script by Tunghsiao Liu

# Please check the wordpress download page and ensure to use the latest version
# http://ja.wordpress.org/
# http://cn.wordpress.org/

# Variables
WP_VER=3.5.2
WP_REMOTE=http://i18n.svn.wordpress.org
WP_EXCLUDE=--exclude=.*
WP_TMP=/tmp/wp-lang
WP_DIST=/srv/www/postholic.com/public_html/wp-content

# Download original translated packages
echo " - Downloading WordPress packages..."
wget -qN http://cn.wordpress.org/wordpress-$WP_VER-zh_CN.zip -P $WP_TMP/ -a $WP_TMP/wget.log -d
wget -qN http://ja.wordpress.org/wordpress-$WP_VER-ja.zip -P $WP_TMP/ -a $WP_TMP/wget.log -d

# Unpack
echo " - Unpacking zipball..."
unzip -qqo $WP_TMP/wordpress-$WP_VER-zh_CN.zip -d $WP_TMP/cn/
unzip -qqo $WP_TMP/wordpress-$WP_VER-ja.zip -d $WP_TMP/ja/

# Remove junk files generated by official Chinese translaters
echo " - Removing junk files generated by official Chinese translaters..."
rm -rf $WP_TMP/cn/wordpress/wp-content/languages/zh_CN*.css
rm -rf $WP_TMP/cn/wordpress/wp-content/languages/zh_CN*.js
rm -rf $WP_TMP/cn/wordpress/wp-content/languages/zh_CN*.php

# Re-translate original language files
# You need to have gettext installed on your server in order to use msgfmt
# Useful command: cat zh_CN.po | grep '自豪'
# Theme specified strings come first, then replace all common strings using *zh_CN.po mask
echo " - Re-translating original language files..."

# Twenty Twelve
echo "   - Re-translating Twenty Twelve..."
cd $WP_TMP/cn/wordpress/wp-content/languages/themes/
for file in `find . -name "twentytwelve-zh_CN.po"` ; do msgfmt -o `echo $file | sed s/\.po/\.mo/` $file ; done

# Twenty Eleven
echo "   - Re-translating Twenty Eleven..."
cd $WP_TMP/cn/wordpress/wp-content/languages/themes/
sed -i 's/"特色"/"推荐文章"/g' twentyeleven-zh_CN.po
sed -i 's/"特色/"推荐/g' twentyeleven-zh_CN.po
sed -i 's/msgstr "查看所有由 %s 发布的文章"/msgstr "查看所有由 %s 发表的文章"/g' twentyeleven-zh_CN.po
sed -i 's/包含 <a %1$s>%2$s 张图像<\/a>/包含 <a %1$s>%2$s 张图片<\/a>/g' twentyeleven-zh_CN.po
sed -i 's/图像导航/图片导航/g' twentyeleven-zh_CN.po
sed -i 's/多媒体陈列厅/相册/g' twentyeleven-zh_CN.po
sed -i 's/早期文章/较老文章/g' twentyeleven-zh_CN.po
sed -i 's/将内容置于左侧/内容在左侧/g' twentyeleven-zh_CN.po
sed -i 's/将内容置于右侧/内容在右侧/g' twentyeleven-zh_CN.po
sed -i 's/一栏、不带边栏/单栏、无侧栏/g' twentyeleven-zh_CN.po
sed -i 's/有点尴尬诶。/有点儿尴尬，不是吗？/g' twentyeleven-zh_CN.po
sed -i 's/《%2$s》上有 %1$s 条评论/%1$s 条「%2$s」的回复/g' twentyeleven-zh_CN.po
for file in `find . -name "twentyeleven-zh_CN.po"` ; do msgfmt -o `echo $file | sed s/\.po/\.mo/` $file ; done

# Twenty Ten
echo "   - Re-translating Twenty Ten..."
cd $WP_TMP/cn/wordpress/wp-content/languages/themes/
for file in `find . -name "twentyten-zh_CN.po"` ; do msgfmt -o `echo $file | sed s/\.po/\.mo/` $file ; done

# Core language files and all other common translations for themes, based on Twenty Ten.
echo "   - Re-translating core language files..."
cd $WP_TMP/cn/wordpress/wp-content/languages/
sed -i 's/Last-Translator: Jimmy Xu <me@jimmyxu.org>/Last-Translator: Tunghsiao Liu <t@postholic.com>/g' *zh_CN.po
sed -i 's/Language-Team: WordPress China/Language-Team: WordPress China and Postholic Dev Team/g' *zh_CN.po
sed -i 's/"%1$s%2$s"/"%1$s @ %2$s"/g' *zh_CN.po
sed -i 's/中文支持论坛/支持论坛/g' *zh_CN.po
sed -i 's/自豪地采用 %s/由 %s 驱动/g' *zh_CN.po
sed -i 's/链向 %s 的固定链接/「%s」的永久链接/g' *zh_CN.po
sed -i 's/cn.wordpress.org/wordpress.org/g' *zh_CN.po
sed -i 's/仪表盘/控制台/g' *zh_CN.po
sed -i 's/归档/存档/g' *zh_CN.po
sed -i 's/月度/月份/g' *zh_CN.po
sed -i 's/固定链接/永久链接/g' *zh_CN.po
sed -i 's/博客/网志/g' *zh_CN.po
sed -i 's/分类目录/分类/g' *zh_CN.po
sed -i 's/小工具/小挂件/g' *zh_CN.po
sed -i 's/引语/引用/g' *zh_CN.po
sed -i 's/特性筛选/特征筛选/g' *zh_CN.po
sed -i 's/设为特色图像/设置特色图像/g' *zh_CN.po
sed -i 's/插入多媒体/插入媒体/g' *zh_CN.po
sed -i 's/拖文件到任何地方来上传/拖文件至任意位置上传/g' *zh_CN.po
sed -i 's/“/「/g' *zh_CN.po
sed -i 's/”/」/g' *zh_CN.po
sed -i 's/《/「/g' *zh_CN.po
sed -i 's/》/」/g' *zh_CN.po
for file in `find . -name "*zh_CN.po"` ; do msgfmt -o `echo $file | sed s/\.po/\.mo/` $file ; done

# Copy re-translated files
echo " - Copying re-translated files to prod. site..."
cp -R $WP_TMP/cn/wordpress/wp-content/languages/ $WP_DIST/
cp -R $WP_TMP/ja/wordpress/wp-content/languages/ $WP_DIST/

# Cleanup
echo " - Cleaning up temporary files..."
rm -rf $WP_TMP/cn/
rm -rf $WP_TMP/ja/

echo " - Done."
